# Server Configuration
server.port=8080

# Database Configuration (Defaults, will need update)
spring.datasource.url=jdbc:postgresql://localhost:5432/foodshield
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security
# Generating a random secret for now, will move to env var in prod
foodshield.app.jwtSecret=FoodShieldSecretKeyForJWTGenerationShouldBeLongAndComplex
foodshield.app.jwtExpirationMs=86400000

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
foodshield.app.corsQueryString=http://localhost:5173
